name: Release
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
jobs:
  # publish_on_linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 14
  #   - name: install dependencies
  #     run: npm install
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish

  # publish_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 14
  #   - name: install dependencies
  #     run: npm install
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish

  publish_on_win:
    # https://github.com/actions/runner/issues/1007#issuecomment-808904408
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    permissions:
      contents: write

    # https://github.com/MadLittleMods/node-usb-detection/pull/165/files
    runs-on: windows-2019
    environment: ReleaseEnv
    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      # - name: Publish Binaries
      #   run: npm run publish

      - name: Prepare publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish -- --dry-run

      # - name: Sign EXE with CodeSignTool
      #   uses: sslcom/esigner-codesign@develop
      #   with:
      #     # Sign and timestamp code object.
      #     command: sign
      #     username: ${{ secrets.ES_USERNAME }}
      #     password: ${{ secrets.ES_PASSWORD }}
      #     credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
      #     totp_secret: ${{ secrets.ES_TOTP_SECRET }}
      #     file_path: ${GITHUB_WORKSPACE}/out/starcitizen-byecache-win32-x64/starcitizen-byecache.exe
      #     override: true

      # TODO set app version dynamically
      # Name has a space and it breaks at the moment
      - name: Sign Setup EXE with CodeSignTool
        uses: sslcom/esigner-codesign@develop
        with:
          # Sign and timestamp code object.
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          credential_id: ${{ secrets.ES_CREDENTIAL_ID }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: ${GITHUB_WORKSPACE}/out/make/squirrel.windows/x64/starcitizen-byecache-0.1.0^ Setup.exe
          override: true

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish -- --from-dry-run