name: Release
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:
jobs:
  # publish_on_linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 14
  #   - name: install dependencies
  #     run: npm install
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish

  # publish_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 14
  #   - name: install dependencies
  #     run: npm install
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish

  publish_on_win:
    # https://github.com/actions/runner/issues/1007#issuecomment-808904408
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    permissions:
      contents: write

    # https://github.com/MadLittleMods/node-usb-detection/pull/165/files
    runs-on: windows-2019
    environment: ReleaseEnv
    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Prepare exe
        # runs package and make
        run: npm run make

      - name: Sign EXE with CodeSignTool
        uses: sslcom/esigner-codesign@develop
        with:
          # Sign and timestamp code object.
          command: sign
          username: ${{ secrets.ES_USERNAME }}
          password: ${{ secrets.ES_PASSWORD }}
          totp_secret: ${{ secrets.ES_TOTP_SECRET }}
          file_path: ${GITHUB_WORKSPACE}/out/starcitizen-byecache-win32-x64/${{env.PROJECT_NAME}}.exe

      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
